// <auto-generated />
using System;
using Egg_Pedict_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Egg_Pedict_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250314060219_addnewtable")]
    partial class addnewtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Egg_Pedict_BackEnd.Model.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Egg_count")
                        .HasColumnType("double precision");

                    b.Property<double>("Feed_Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Health_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Hen_Age_weeks")
                        .HasColumnType("double precision");

                    b.Property<double>("Hen_Count")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("Light_Hours")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("Egg_Pedict_BackEnd.Model.hen_production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Egg_count")
                        .HasColumnType("double precision");

                    b.Property<double>("Feed_Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Health_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Hen_Age_weeks")
                        .HasColumnType("double precision");

                    b.Property<double>("Hen_Count")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("Light_Hours")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("hen_production");
                });
#pragma warning restore 612, 618
        }
    }
}
